version: '3.7'
services:
  apimovies_app:
    build:
      context: .
    depends_on:
      - apimovies_bd
    restart: on-failure
    ports:
      - 8000:8000
      - 8084:8080
    environment:
      - TZ= "America/Argentina/Buenos_Aires"
      - SPRING_DATASOURCE_URL=jdbc:mysql://apimovies_bd:3306/movies_db?useSSL=false
      - SPRING_DATASOURCE_USERNAME=user_db
      - SPRING_DATASOURCE_PASSWORD=user_db
      - SPRING_JPA_SHOW_SQL=TRUE
      - LOGGING_LEVEL_ROOT=INFO

  apimovies_bd:
    image: mysql:5.7
    ports:
      - 3307:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=user_db
      - MYSQL_PASSWORD=user_db
      - MYSQL_DATABASE=movies_db
      - TZ= "America/Argentina/Buenos_Aires"
    command: ['mysqld', '--default-time-zone=-03:00']
    volumes:
      - "../data/apimovies:/var/lib/mysql"